# Prometheus configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'rwa-monitor'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  # - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Backend API metrics
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3001']
        labels:
          service: 'backend-api'
    metrics_path: '/metrics'

  # PostgreSQL exporter (if added)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
        labels:
          service: 'postgresql'

  # Redis exporter (if added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
        labels:
          service: 'redis'

  # Node exporter for host metrics (if added)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-exporter'

  # Nginx metrics (if nginx exporter is added)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
        labels:
          service: 'nginx'